#!/usr/bin/env node

'use strict';

var cli = require('commander');
var rek = require('rekuire');
var logger = rek('logger');
var version = rek('package.json').version;
var dupes_read_cli = rek('dupes-read.js');

cli
  .version(version)
  .usage('[filepath] [-hVjqv]')
  .option('-j, --show-json', 'show full json result')
  .option('-q, --quiet', 'print only duplicates list')
  .option('-v, --verbose', 'print progression and statistics')
  .parse(process.argv);

logger.setVerbosity(cli.quiet ? 0 : cli.verbose ? 2 : 1);

var targets = process.argv.slice(2).filter(function(v) { return v.indexOf('-') != 0; });
if (targets.length >= 2) {
  return logger.error('Too many arguments!! Besides flags, there can be only one!');
}

dupes_read_cli.show({
  target: targets[0],
  showJson: cli.showJson
});
