#!/usr/bin/env node

'use strict';

var cli = require('commander');
var clc = require('cli-color');
var rek = require('rekuire');
var version = rek('package.json').version;
var dupes_read = rek('dupes-read.js');

cli
  .version(version)
  .usage('[filepath] [-hVjls]')
  .option('-j, --show-json', 'show full json result')
  .option('-l, --list', 'print only duplicates list')
  .option('-s, --statistics', 'print only progression and statistics')
  .parse(process.argv);

var targets = process.argv.slice(2).filter(function(v) { return v.indexOf('-') != 0; });
if (targets.length >= 2) {
  return console.log(clc.red('Too many arguments!! Besides flags, there can be only one!'));
}

dupes_read.show({
  target: targets[0],
  showJson: cli.showJson,
  onlyList: cli.list && !cli.statistics,
  onlyStats: cli.statistics && !cli.list
});
