#!/usr/bin/env node

'use strict';

var cli = require('commander');
var rek = require('rekuire');
var utils = rek('utils');
var dupes = rek('dupes.js');
var version = rek('package.json').version;

cli
  .version(version)
  .usage('[directory] [-hVelsq] [--overwrite --no-write --file=filename]')
  .option('-e, --include-empty', 'include empty files')
  .option('-l, --list', 'print only duplicates list')
  .option('-s, --statistics', 'print only progression and statistics')
  .option('-q, --quiet', 'do not print output')
  .option('--file <filename>', 'write results to a different file, use with "=": "--file="report.json"')
  .option('--no-write', 'do not write results file')
  .option('--overwrite', 'overwrite existing results file. use with --write')
  .parse(process.argv);


var targets = process.argv.slice(2).filter(function(v) { return v.indexOf('-') != 0; });
if (targets.length >= 2) {
  utils.fatalError('Too many arguments!! Besides flags, there can be only one!');
}

dupes.findDupes({
  target: targets[0],
  includeEmpty: cli.includeEmpty,
  fileName: cli.file || 'dupes.json',
  write: cli.write,
  overwrite: cli.overwrite,
  printList: !cli.statistics && !cli.quiet,
  printStats: !cli.list && !cli.quiet
});
