#!/usr/bin/env node

'use strict';

var cli = require('commander');
var rek = require('rekuire');
var logger = rek('logger');
var version = rek('package.json').version;
var dupes_cli = rek('dupes-cli');

cli
  .version(version)
  .usage('[directory] [-hVeqvw] [--overwrite --no-write --file=filename]')
  .option('-e, --include-empty', 'include empty files')
  .option('-q, --quiet', 'do not print normal output')
  .option('-v, --verbose', 'print extra output')
  .option('-f, --file <filename>', 'write results to a different file, use with "=": "--file="report.json"')
  .option('--no-write', 'do not write results file')
  .option('--overwrite', 'overwrite existing results file. use with --write')
  .parse(process.argv);

logger.setVerbosity(cli.quiet ? 0 : cli.verbose ? 2 : 1);

var targets = process.argv.slice(2).filter(function(v) { return v.indexOf('-') != 0; });
if (targets.length >= 2) {
  return logger.error('Too many arguments!! Besides flags, there can be only one!');
}

dupes_cli.findDupes({
  target: targets[0],
  includeEmpty: cli.includeEmpty,
  fileName: cli.file || 'dupes.json',
  write: cli.write,
  overwrite: cli.overwrite
});
